version: "3.9"

# app(Django),web(Nginx)のコンテナを作成
services:
  app:
    # コンテナ名をdjangoに設定
    container_name: Django
    # DjangoのDockerfileをビルドする
    build: 
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: Docker/Django/Dockerfile
    volumes:
      - ./Django_App:/code
      - ./static:/static
    # 8000番ポートをNginx側が接続できるよう開く
    expose:
      - "8000"
    # uWSGIを起動させる
    command:  bash -c "python manage.py collectstatic --noinput && \
              uwsgi --socket :8000 --module Blearn.wsgi --py-autoreload 1 --logto /tmp/mylog.log"
    env_file:
      - .env.prod

  web:
    # コンテナ名をnginxに指定
    container_name: Nginx
    # NginxのDockerfileをビルドする
    build:
      # ビルドコンテキストはカレントディレクトリ
      context: .
      dockerfile: Docker/Nginx/Dockerfile
    # ボリュームを指定
    # ローカルの/staticをコンテナの/staticにマウントする
    volumes:
      - ./Docker/Nginx/conf:/etc/nginx/conf.d
      - ./Docker/Nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    # ローカルの80番ボートをコンテナの80番ポートとつなぐ
    ports:
      - "80:80"
    # 先にappを起動してからwebを起動する
    depends_on:
      - app


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # コンテナ内の環境変数を.envを使って設定
    env_file:
      - .env.prod
    ports:
      - 4000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
      
volumes:
  mysql_data:
  static: